### PR TITLE
Jetpack updates added

### PR DESCRIPTION
**Pull request by jjloomis**
Hey Sparanoid. These are the latest Jetpack updates (3.7.1 and 3.7.2) added to Slimpack. I did a diff on the new version of Jetpack and Slimpack. I added the changes to my local repo of Slimpack and published the changes here. (Should I have forked the project, made the changes on a clone of my fork and then submitted the pull request from my GitHub account? I'm obviously still new to how this works.)

This is my first time contributing to anything on GitHub. I'd definitely like to do more, so I'll welcome any constructive criticism of my approach.

### CODE REVIEW

**Comment by jjloomis** [comment]
Hey Sparanoid. What are the next steps in the process? Do you review my commits and then merge them with the master branch? I see a "Merge pull request" button (above this box) but because Slimpack is your project/ plugin, I want to leave those decisions to you.

(Again, I'm new to this.)

**Comment by sparanoid** [comment]
I'm really appreciate your work, it's busy these days to me so I'll review it later this week.

**Comment by sparanoid** [comment]
@jjloomis As a collaborator, you don't need to fork this project, you can push changes directly to this repo, just create a new branch for new updates.

Also I'm just curious did all these changes and commit manually? How long did you take to complete this process? I'm afraid you'll feel boring if you manually did all these :)

**Comment by jjloomis** [comment]
Thanks @sparanoid. I did do all of the changes manually. (Made the change in my repo and then did the commit in GitHub Desktop.) I think it took about 1-2 hours (while I was doing other stuff--watching TV, on Facebook, etc.) I don't think it's boring. I figure I have to start somewhere. 

Is there a faster way to approach this?

**Comment by sparanoid** [comment]
@jjloomis Cool, previously I copied all needed files and diff'ed them in [Tower](http://www.git-tower.com/) and created just one commit, it's really appreciate you diff them in separate commits.

Can you also give me your username at WordPress.org?

**Comment by jjloomis** [comment]
Hey @sparanoid. I'm jjloomis over on WordPress.org too.

**Comment by jjloomis** [comment]
@sparanoid awesome. I'll follow the same pattern with the future updates to Jetpack. Thanks for letting me work on this.

**Comment by sparanoid** [comment]
@jjloomis you are welcome! One last thing, I'm using [GaryJones/wordpress-plugin-git-flow-svn-deploy](https://github.com/GaryJones/wordpress-plugin-git-flow-svn-deploy) to deploy changes from this git repo to WordPress.org SVN repo. I've added you as a contributor on WordPress.org so you can test if you have permission to publish this plugin?

**Comment by jjloomis** [comment]
@sparanoid no problem. I should be able to do this later tonight. Since I've never published a plugin to WordPress.org before: If I publish the same plugin with no changes, that will not prompt users to download a new version of the plugin, right (because the version number, etc. will be same)?

**Comment by sparanoid** [comment]
@jjloomis yes, you can just do some minor changes to readme and nothing should happen to users.

**Comment by jjloomis** [comment]
@sparanoid I did a minor change to the readme and used the script to push my local repo of Slimpack (newest version--with my change) to the WordPress.org SVN repo. Then I downloaded a copy of Slimpack from WordPress.org, but the change wasn't there. I will note: I do not have Git-Flow installed on my machine. Might that be the issue? Is Git-Flow necessary in order for the script to work?

**Comment by sparanoid** [comment]
@jjloomis it seems no commits are pushed to WordPress.org: https://plugins.trac.wordpress.org/log/slimpack/, can you post your script shell output?

**Comment by jjloomis** [comment]
@sparanoid I think I know what I was doing wrong last night, but now I'm trying again and seeing this in my terminal (let me know if you want me to paste everything in here):

Sending        README.txt
Transmitting file data .svn: E195023: Commit failed (details follow):
svn: E195023: Changing file '/private/tmp/slimpack/trunk/README.txt' is forbidden by the server
svn: E175013: Access to '/!svn/txr/1263180-smts/slimpack/trunk/README.txt' forbidden

**Comment by jjloomis** [comment]
@sparanoid as a side note: my change does appear here on GitHub (add !! to line 160).

**Comment by sparanoid** [comment]
@jjloomis So it seems that only project owner of the plugin has the permission to push updates to WordPress.org repo. That's fine, I will keep an eye on this project and feel free to mention me on GitHub or just email me if I missed something.

**Comment by jjloomis** [comment]
@sparanoid okay sounds good. I"ll be watching Jetpack for updates. Thanks again.

**Comment by jjloomis** [comment]
Hey @sparanoid. I see there's a new version of Jetpack. I'll be adding those updates to Slimpack in the next couple of days. Don't want you to think I'm slackin'. Haha.

**Comment by sparanoid** [comment]
@jjloomis cool :+1:

**Pull request merged**
